package ihk.professor.dao;

public class Sql {
	
	public static final String SELECT_BY_PROFESSOR_PNO_SQL =
			"SELECT P.PNO AS PNO, P.PASSWORD AS PASSWORD, P.TEL AS TEL, P.NAME AS NAME, P.ADDRESS AS ADDRESS, P.EMAIL AS EMAIL, D.NAME AS DNAME FROM PROFESSOR P INNER JOIN DEPARTMENT D ON P.DNO = D.DNO WHERE P.PNO = ?";
	
	public static final String UPDATE_PROFESSOR_INFO_SQL =
			"UPDATE PROFESSOR SET PASSWORD = ?, NAME = ?, ADDRESS = ?, TEL = ?, EMAIL = ? WHERE PNO = ? ";

}
